package edu.byu.mealplanningassistant.models

import java.util.*

/**
 * @author Chris West (Chris4942)
 */
data class Recipe (
    /** Recipe ids should follow the form R_<RandomStringOfChars> and will be randomly generated by the backend */
    val id: String,
    val name: String,
    /** Refers to a username */
    val owner: String,
    /** date the recipe was put into the db */
    val date: Long,
    val ingredients: Map<String, Amount>,
    val instructions: List<String>,
    val tags: SortedSet<String>, 
    /** Number of people this recipe can serve */
    val servingsProduced: Number,
    /** calories per serving */
    val calories: Number?,
    val macronutrients: Map<Macronutrient, Amount>?,
    val rating: Number,
)

data class Amount (
    val amount: Number,
    val unit: Unit,
        )

enum class Unit {
    GRAMS,
    MG,
    LITERS,
    ML,
    CUPS,
    TSP,
    TBSP,
    OZ,
    // TODO add more as needed
}

enum class Macronutrient {
    FAT,
    TRANS_FAT,
    SAT_FAT,
    CARBOHYDRATES,
    SUGAR,
    PROTEIN,
    CHOLESTEROL,
    SODIUM,
    // TODO add more as needed
}